# Generated by Django 4.1.3 on 2022-11-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_tag_alter_review_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(blank=True, to="projects.tag"),
        ),
    ]
